version: '3.7'

volumes:
  db:
  scalar:

services:
  scalar:
    build:
      context: .
    ports:
      - 4000:80
    volumes:
      - scalar:/var/www/html/uploads
    environment:
      - SCALAR_ENVIRONMENT=development
      - SCALAR_DB_HOSTNAME=db
      - SCALAR_DB_USERNAME=scalar
      - SCALAR_DB_PASSWORD=scalar_db_password
      - SCALAR_DB_DATABASE=scalar
      - SCALAR_ENCRYPTION_KEY='top secret shhhh'
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=scalar
      - MYSQL_USER=scalar
      - MYSQL_PASSWORD=scalar_db_password
    command: ['--default-authentication-plugin=mysql_native_password']
    restart: always
